ZEROSHOT_QA_PROMPT = '''Please answer the question regarding a visual feature of an organism (animal, plant, etc.). Please follow the answer format: “Answer: {answer_text}”
Question:'''

QA_PROMPT_COT = '''Given a question from the user regarding a visual feature of an organism (animal, plant, etc.), answer it using systematic reasoning. You will be provided with one or more images that may contain the key information for answering the question. Your output should consist of two parts.

1. Reasoning:
   - Look at the image carefully. Pick out the feature that can help you correctly answer the question.
   - If no useful information can be inferred from the image, you should summarize your own knowledge related to the question.
   - If the image contradicts your own knowledge, you should trust the image.
   - If the image is blurry, you should summarize your own knowledge related to the question.

2. Answer:
   - Only your conclusion that directly answers the question.
   - No need to repeat the reasoning.

Please always follow the answer format without bolding texts: "### Reasoning: {reasoning}\n### Answer: {your_answer}"
'''

EVAL_PROMPT='''Please evaluate the answer to a question, score from 0 to 1. The reference answer is provided, and the reference is usually short phrases or a single keyword. If the student answer is containing the keywords or similar expressions (including similar color), without any additional guessed information, it is full correct. If the student answer have missed some important part in the reference answer, please assign partial score. Usually, when there are 2 key features and only 1 is being answered, assign 0.5 score; if there are more than 2 key features, adjust partial score by ratio of correctly answered key feature. The reference answer can be in the form of a Python list, in this case, any one of the list item is correct. \nIf student answer contain irrelevant information not related to question, mark it with \"Redundant\", but it does not affect score if related part are correct. (e.g. Question: what shape is leave of Sanguinaria canadensis, Student Answer: shape is xxx, color is yyy, this is Redundant answer)\nIf student answer contain features not listed in reference answer, mark it with \"Likely Hallucination\" and deduct 0.5 score. (e.g., Reference Answer: black and white. Student Answer: black white, with yellow dots, “yellow dots” is not mentioned in reference). The reference answer sometimes contains an add-on enclosed by brackets (), to help verifying hallucinations (e.g.: “shape is xxx (color is yyy)”). Not mentioning add-on information in answer is not considered wrong. Answering \"I don't know\", \"Not enough information\" is considered wrong.\nFormat Instructions: Separate the remarks with score using \"|\", that is, use the syntax of: \"Score: {score} | Likely Hallucination\", \"Score: {score}\", \"Score: {score} | Likely Hallucination | Redundant\". If any explanation on why giving the score is needed, do not start a new line and append after remark with brackets, e.g. \"Score: {score} | Redundant | (Explanation: abc)\".\n\nFollowing are few examples:\n\n'''
EVAL_PROMPT_DEMO = "Question: Is there any specific color marking around the eyes of a semipalmated plover (scientific name: Charadrius semipalmatus)?\nReference Answer: black eye-round feather, white stripe above eyes. (sometimes connected to the white forehead)\n\nStudent Answer: Yes, the bird has a distinctive black line that runs through the eye, which is a key identifying feature.\nScore: 0 | Likely Hallucination\n\nStudent Answer: They have a black vertical band in front of the eye, a white band above the eye, and a single black band that wraps partially around the eye, creating a partial \"mask\" appearance.\nScore: 1\nStudent Answer: Yes, the semipalmated plover has a distinctive black/dark ring around its eye, surrounded by a bright white ring or patch\nScore: 0.5 | Likely Hallucination (Explanation: not white ring, but only a line above the eye)\n\n\nQuestion: What is the typical color of the antennae of Harris's checkerspot butterfly (scientific name: Chlosyne harrisii)?\nReference Answer: alternating black and white band, with yellow on the tip\n\nStudent Answer: The antennae of Harris's checkerspot butterfly are black with orange-tipped clubs.\nScore: 0.5 (Explanation: not mentioning black and white)\n\nStudent Answer: The typical color of the antennae of Harris's checkerspot butterfly is black with white spots.\nScore: 0.5 | Likely Hallucination (Explanation: not white spot but band. Not mentioning the tip)\n\n\nQuestion: Are the leaves of burro-weed (scientific name: Ambrosia dumosa) usually covered in small hairs?\nReference Answer: yes\n\nStudent Answer: Yes, the leaves of burro-weed (Ambrosia dumosa) are typically covered in small hairs, giving them a grayish or whitish-green appearance.\nScore: 1 | Redundant\n\n\nNow, Score the following question:\n\n"
